revoke all on function public.is_event_organizer() from public, anon, authenticated, service_role;
revoke all on function public.event_user_can_manage(uuid, uuid) from public, anon, authenticated, service_role;
revoke all on function public.event_user_can_view(uuid, uuid) from public, anon, authenticated, service_role;
revoke all on function public.event_issue_order_tickets(uuid) from public, anon, authenticated, service_role;
revoke all on function public.reserve_event_order(jsonb, uuid) from public, anon, authenticated, service_role;
revoke all on function public.finalize_event_order(uuid, text, text, text) from public, anon, authenticated, service_role;
revoke all on function public.release_event_order_hold(uuid, text) from public, anon, authenticated, service_role;
revoke all on function public.refund_event_order(uuid) from public, anon, authenticated, service_role;
revoke all on function public.register_event_rsvp(uuid, text) from public, anon, authenticated, service_role;
revoke all on function public.cancel_event_rsvp(uuid) from public, anon, authenticated, service_role;
revoke all on function public.claim_event_invitation(text) from public, anon, authenticated, service_role;
revoke all on function public.check_in_event_ticket(uuid, text) from public, anon, authenticated, service_role;
revoke all on function public.undo_event_ticket_check_in(uuid) from public, anon, authenticated, service_role;
revoke all on function public.get_event_ticket_secret(uuid) from public, anon, authenticated, service_role;
revoke all on function public.event_set_updated_at() from public, anon, authenticated, service_role;
revoke all on function public.admin_update_user_profile(uuid, text, text, text, text, text) from public, anon, authenticated, service_role;

grant execute on function public.is_event_organizer() to authenticated, service_role;
grant execute on function public.event_user_can_manage(uuid, uuid) to authenticated, service_role;
grant execute on function public.event_user_can_view(uuid, uuid) to anon, authenticated, service_role;
grant execute on function public.reserve_event_order(jsonb, uuid) to authenticated, service_role;
grant execute on function public.register_event_rsvp(uuid, text) to authenticated, service_role;
grant execute on function public.cancel_event_rsvp(uuid) to authenticated, service_role;
grant execute on function public.claim_event_invitation(text) to authenticated, service_role;
grant execute on function public.check_in_event_ticket(uuid, text) to authenticated, service_role;
grant execute on function public.undo_event_ticket_check_in(uuid) to authenticated, service_role;
grant execute on function public.event_issue_order_tickets(uuid) to service_role;
grant execute on function public.finalize_event_order(uuid, text, text, text) to service_role;
grant execute on function public.release_event_order_hold(uuid, text) to service_role;
grant execute on function public.refund_event_order(uuid) to service_role;
grant execute on function public.get_event_ticket_secret(uuid) to service_role;
grant execute on function public.admin_update_user_profile(uuid, text, text, text, text, text) to authenticated, service_role;
